version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    environment:
      - "IN_DOCKER_COMPOSE=true"
  db:
    build: ./docker/postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/
  redis:
    build: ./docker/redis
    ports:
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
