name: Upload Source Maps to Rollbar
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install
      - run: npm run build
      - run: chmod +x "${GITHUB_WORKSPACE}/.github/upload-source-maps-to-rollbar.sh"
      - run: "${GITHUB_WORKSPACE}/.github/upload-source-maps-to-rollbar.sh"
